### ISSUE TITLE
fatal error: lua.h: No such file or directory #include <lua.h>

### ISSUE THREAD

**Issue by Waqar731** [jsburklund/RobotAggregation#1]
Hello Sir,
I have downloaded some your code of ARGoS, from the web [https://github.com/jsburklund/RobotAggregation]
After downloading I am trying to execute the code, but during the phase of " make  "I am getting the following error.
how to solve this problem? While this is not the programatical error.

I have attached the error message on terminal below.

![Screenshot from 2019-06-05 14-44-15](https://user-images.githubusercontent.com/8842689/59011568-a631ea00-8824-11e9-9ea5-7340c0e83c9c.png)

Thanks & Regards

**Comment by PeterMitrano** [comment]
try `sudo apt install liblua5.3-dev`

**Comment by Waqar731** [comment]
Thanks for reply!
I have removed the error after installing the lua. After this, I build the code successfully. After compiling when I write the command to execute the simulation, then I got the following error of loop function.
**Please would you like to tell me that how to solve this problem?**

![Screenshot from 2019-06-07 15-40-30](https://user-images.githubusercontent.com/8842689/59104232-8bdd3680-8920-11e9-907f-2e33a1a326e2.png)

**Comment by PeterMitrano** [comment]
what command did you run? looks like an error in parsing the experiment file you gave it

**Comment by Waqar731** [comment]
Hello sir,
First of all, I move into the directory of RobotAggregation using following command:
`cd RobotAggregation`
Second, I write the following line in terminal to start the simulation.
` argos3 -c experiments/two_kin.argos`

I also attached the image of terminal below:
![Screenshot from 2019-06-08 08-22-17](https://user-images.githubusercontent.com/8842689/59141449-bcfb4c80-899c-11e9-90ef-d5cfbcc1f590.png)

**Where am I wrong in the above command to start the simulation?**

Thanks

**Comment by PeterMitrano** [comment]
our argos files aren't designed to be run on their own, but you should be able to run stuff like this:

    ./build/bin/evaluate -t 1 experiments/4_class/40_uniform_0.05_density.argos build/loop_functions/libsegregation_loop_function.so params/new_grid_search.dat -z -s 0

**Comment by Waqar731** [comment]
Thanks a lot, now they are working exactly!

**Comment by WaliaRohan** [comment]
Hi. I had Lua installed and it still wasn't running for me. The problem was that the CMakelists.txt file in this repo wasn't looking for lua. I just made two changes in my CMakelists.txt by following one of the argos examples - 

```cmake_minimum_required(VERSION 2.8.12)
project(minimalist_segregation)

set(CMAKE_CXX_STANDARD 14)

find_package(PkgConfig)
pkg_check_modules(ARGOS REQUIRED argos3_simulator)
set(ARGOS_PREFIX ${ARGOS_PREFIX} CACHE INTERNAL "")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${ARGOS_PREFIX}/share/argos3/cmake)

# Find Lua
find_package(Lua REQUIRED)                                                         #-> CHANGE

include_directories(${CMAKE_SOURCE_DIR} ${ARGOS_INCLUDE_DIRS} ${LUA_INCLUDE_DIR})    #-> ADDED '{LUA_INCLUDE_DIR}'
link_directories(${ARGOS_LIBRARY_DIRS})

add_subdirectory(controllers)
add_subdirectory(loop_functions)
add_subdirectory(bin)
```
